name: Deploy to Github Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      MERMAID_URL: https://github.com/badboy/mdbook-mermaid/releases/download/v0.13.0/mdbook-mermaid-v0.13.0-x86_64-unknown-linux-gnu.tar.gz
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Get mdBook mermaid
        run: wget -O mdbook-mermaid.tar.gz $MERMAID_URL
      - name: Extract mdBook mermaid
        run: tar -xvf mdbook-mermaid.tar.gz
      - name: Install mdBook mermaid
        run: sudo mv mdbook-mermaid /usr/local/bin
      - name: Build
        working-directory: ./book
        run: mdbook build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './book/book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
